### ISSUE TITLE
RenderFeatures not showing in build

### ISSUE THREAD

**Issue by minitruffle** [Kodrin/URP-PSX#9]
Hello, I am using Unity 2020.3.48f and I just built my project. However, when I open the EXE (I'm on windows), the renderfeatures don't seem to work. It works fine in the editor but not in the built version. Just to be clear I have both the renderfeatures on the URP renderer asset and the post-processing effects for dithering and pixelation.

In the editor:
![Screenshot (33)](https://github.com/Kodrin/URP-PSX/assets/64572721/e65433c3-88b9-48a2-adca-74a2a30f05f9)

In the build:
![Screenshot (34)](https://github.com/Kodrin/URP-PSX/assets/64572721/4321d319-3668-47f0-8fb6-c5b753d2122d)

I can provide more screenshots if needed, thanks in advance.

**Comment by xPorcusx** [comment]
Hi @minitruffle , I have the exact same problem right now. How did you fix the issue?

**Comment by montoulieu** [comment]
@minitruffle how did you get this working? I'm having the same issue.

**Comment by Type-32** [comment]
any solutions?

**Comment by Type-32** [comment]
Fixed it by adding this into the Build Setting:
<img width="709" alt="image" src="https://github.com/user-attachments/assets/0ff1d990-45cb-410d-92ed-fe4ad8e7ba4b">
